service: ProjectPeelosiBackend

frameworkVersion: '3'

custom:
  wsgi:
    app: app.EndpointController
#    app: app.app

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements